version: "{build}"

branches:
  only:
    - master

build: off

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler --version
  - bundle install

test_script:
  - bundle exec rspec

environment:
  matrix:
    - ruby_version: '187'
    - ruby_version: '193'
    - ruby_version: '21'

matrix:
  fast_finish: true
